### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by toshibochan** [mrsharpoblunto/it-gets-the-hose-again#1]
please need help for install this on my raspberry pi.
i don't know how to do coding. you have tutorial video on youtube?

**Comment by mrsharpoblunto** [comment]
I don't have any tutorial videos, but you can follow the instructions on setup here https://github.com/mrsharpoblunto/it-gets-the-hose-again/blob/master/web/README.md. You don't need any coding abilities to follow those instructions. Also bear in mind without the hardware additions to the Pi, this app won't do anything :)
