### ISSUE TITLE
need help to install

### ISSUE THREAD

**Issue by toshibochan** [mrsharpoblunto/it-gets-the-hose-again#2]
im trying to install.
npm install -g gulp(okay)
npm install(fail)
-npm ERR! install Couldn't read dependencies
-npm ERR! Darwin 15.3.0
-npm ERR! argv "/user/local/bin/npm" "install"
-npm ERR! node v4.2.4
-npm ERR! npm v2.14.12
-npm ERR! pach /User/toshibo/package.json
-npm ERR! errno -2
-npm ERR! syscall open

-npm ERR! package.json ENOENT: no such file or directory, open '/User/toshibo/package.json'

thanks
toshi

**Comment by mrsharpoblunto** [comment]
You need to run npm install from within the web directory

**Comment by toshibochan** [comment]
what you mean web directory? not use terminal to install?
sorry I'm new ins this!
thanks for help

**Comment by toshibochan** [comment]
oh i see! cd and go to the folder i just install!
thanks

**Comment by toshibochan** [comment]
now cp keys.delfault.js keys.js
cp: keys.default.js: No such file or directory

**Comment by mrsharpoblunto** [comment]
Once again, do it from within the web folder.

**Comment by toshibochan** [comment]
i did from gulp folder

**Comment by mrsharpoblunto** [comment]
https://github.com/mrsharpoblunto/it-gets-the-hose-again/tree/master/web theres a file called keys.default.js in the web folder - if you do an ls in the web folder it should be there. (you also misspelled the file - its keys.default.js, not keys.delfault.js)

**Comment by toshibochan** [comment]
to install this have to do wget https://github.com/mrsharpoblunto/it-gets-the-hose-again?

**Comment by mrsharpoblunto** [comment]
The instructions say to 'cp keys.default.js keys.js'. If you run that command from within the web folder, it will work (because as I mentioned previously, there is a file there called keys.default.js)

To be honest I think you need to brush up on your git & command line basics, & get a basic working knowledge of node.js first otherwise you'll probably find this difficult to get running.

**Comment by toshibochan** [comment]
okay thanks!
